theme: jekyll-theme-cayman
remote_theme: tuur29/pages-themes-cayman
title: Ziqian Xia
description: Meta-analysis, systematic reviews and R Programming.
show_downloads: true
color:
  header: "#FFFFFF"
  gradient_left: "#F3904F"
  gradient_right: "#3B4371"
buttons:
      zip_url: https://Ziqian-xia.github.io
      zip_title: Back to Homepage
      zip_hide: false
      tar_url: http://example.com/
      tar_title: Latest Talk
      tar_hide: true
      github_hide: true # hides "View on Github"
plugins:
  - jekyll-relative-links
